version: '3.7'

services:
  django_gunicorn:
    volumes:
      - ./toy/static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "80:8000"
    depends_on:
      - flask
    restart: always
  nginx:
    build: ./nginx
    volumes:
      - ./toy/static:/static
    ports:
      - "8000:80"
    depends_on:
      - django_gunicorn
    restart: always
  flask:
    build: ./flask
    ports:
      - "5000:5000"
    restart: always

