version: '3.7'

services:
  flask:
    build: ./flask
    ports:
      - 5000:5000
    restart: always

  toy:
    volumes:
      - ./toy/static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "80:8000"
    depends_on:
      - flask
    restart: always

  nginx:
    build: ./nginx
    volumes:
      - ./toy/static:/static
    ports:
      - "8000:80"
    depends_on:
      - toy
    restart: always
